NO exceptions
i am inside finally block
Test completed
